Sprint 2
aberezin97/middle.messenger.praktikum.yandex pull request #2
Opened 2021-10-31 18:22 UTC by aberezin97

2021-11-01 15:57 UTC, bhoodream requested changes
Спасибо за работу, интересный код! У меня есть некоторые замечания, я их постарался максимально подробно расписать в комментариях. Хотелось бы, чтобы ты поработал над ними :)

Также я столкнулся еще с парой проблем при проверке:
- [ ] нет текста ошибок при валидации, нужны человекопонятные ошибки, которые можно увидеть в интерфейсе
- [ ] я убил 5 минут, но так и не подобрал нормальный пароль, который прошел бы валидацию. С регуляркой явно что-то не то :)

2021-11-01 15:57 UTC, bhoodream commented on src/modules/block.ts
> +    this.props = this._makePropsProxy({ ...props, __id: this._id });
Подскажи пожалуйста, зачем нам еще `__id` помимо `this._id` ?

2021-11-01 15:57 UTC, bhoodream commented on src/modules/http.ts
> +      setTimeout(() => reject(), timeout);
Тут наверное надо прерывать запрос, если мы его решили среджектить по таймауту. Сделать это можно с помощью метода `abort` https://developer.mozilla.org/ru/docs/Web/API/XMLHttpRequest/abort

2021-11-01 15:57 UTC, bhoodream commented on src/modules/http.ts
> +      const isDataMethod = method === METHODS.GET || method === METHODS.DELETE;
Есть ощущение, что название `isDataMethod` не очень подходит этой переменной. Учитывая, что если она `true`, то мы шлем запрос без тела (`body`), ну или `data` в нашем случае, то кажется ей бы лучше называться `isNotDataMethod`

2021-11-01 15:57 UTC, bhoodream commented on src/pages/chat/chat.ts
> +      messages: this.props.messages.map((message: ReceivedMessage | SentMessage) => message).join(''),
Не очень понял зачем было прогонять `.map(...)`, если по итогу ты в мапе ничего не делаешь, а потом просто джоинишь все?

По идее достаточно было `this.props.messages.join('')`.

Если у тебя там проблемы с типами, думаю можно было сделать так:
`(this.props.messages as (ReceivedMessage | SentMessage)[]).join('')`

Или проще:
`(this.props.messages as string[]).join('')`

2021-11-01 15:57 UTC, bhoodream commented on src/pages/chat/index.ts
> +setTimeout(() => {
Подскажи пожалуйста, зачем этот `timeout`?

2021-11-01 15:57 UTC, bhoodream commented on src/pages/profile/profile-change-password/profile-footer/profile-footer.ts
> +                element.dispatchEvent(new Event('focus'));
Очень странно выглядит костыль с триггером `focus/blur` событий на инпуте, просто для того чтобы провести валидацию. У этого подхода могут быть неприятные подводные камни, я бы рекомендовал уходить от него.

Кажется правильнее было бы завести у этого компонента состояние `active` и закидывать его сюда снаружи, через пропсы, и уже отталкиваясь от него блокировать кнопку.

2021-11-01 15:57 UTC, bhoodream commented on src/pages/signin/signin.ts
> +            check.forEach((id) => {
Код проверок `checks` задублирован и повторяется на каждой странице, было бы думаю лучше завести утилиту, которая бы проводила эту проверку... Вроде бы вполне себе адекватная абстракция получилась бы

2021-11-01 15:57 UTC, bhoodream commented on src/styles/chat.scss
> +  .leftpanel {
Нет необходимости вкладывать такие селекторы внутрь, их лучше делать уникальными (как это делается в БЭМ), что-то типа `.chat__leftpanel`. 

Если не уникализировать селекторы, могут быть серьезные проблемы с коллизиями, которые решаются как раз подходом БЭМ в именовании, либо уже более интересными инструментами типа `CSS Modules`, ну или вообще без селекторов через `CSS in JS`.

2021-11-01 15:57 UTC, bhoodream commented on src/styles/chat.scss
> +}
Файл стилей получился слишком большой, такое сопровождать будет очень проблематично. Лучше дробить файлы стилей также на компоненты, в данном случае, это `Chat`, `ChatLeftPanel`, `ChatRightPanel`, `ChatConversation` и тп. Получатся файлы по 50-100 строк.

Также не рекомендую слишком злоупотреблять вложенностью, потому что это сильно вредит читабельности коду, а соответственно и будущему сопровождению. На практике могу сказать, что 2-3 уровня еще нормально (и то, только в случае модификаторов, псевдо(классов/элементов), медиа выражений и тп. 

Вложенность полноценных элементов должна быть вообще нулевой, то есть каждый блок стилей должен содержать только те стили, которые относятся к одному элементу.

2021-11-01 16:07 UTC, aberezin97 commented on src/components/button/button.ts
> +    super('div', props);
Чтобы event вложенные работали, я через uuid в последствии подменяю эти элементы в dom.

2021-11-01 16:19 UTC, aberezin97 commented on src/modules/block.ts
> +    if (oldProps) return true;
Сделал чтобы tsc не ругался, смысла нет никакого :)

2021-11-01 16:26 UTC, aberezin97 commented on src/components/button/button.ts
> +    super('div', props);
То есть по факту без разницы какой элемент был создан, он его подменит на тот что в шаблоне

2021-11-04 17:42 UTC, aberezin97 commented on src/modules/block.ts
> +    this.props = this._makePropsProxy({ ...props, __id: this._id });
Не нужен, скопировал из практикума, забыл удалить :)

2021-11-04 21:51 UTC, aberezin97 commented on src/pages/chat/index.ts
> +setTimeout(() => {
Просто, чтобы показать, что при изменении пропсовов блоки ререндерятся

2021-11-04 22:15 UTC, aberezin97 commented on src/pages/profile/profile-change-password/profile-footer/profile-footer.ts
> +                element.dispatchEvent(new Event('focus'));
Не совсем понял, у самой кнопки сделать это состояние или у инпута?

2021-11-05 06:11 UTC, bhoodream commented on src/pages/profile/profile-change-password/profile-footer/profile-footer.ts
> +                element.dispatchEvent(new Event('focus'));
Состояние по идее у кнопки, чтобы блокировать, если не валидно. В этом состоянии как раз и будет результат валидации, если валидно то активно, нет, не активно. В таком случае валидацию можно сделать снаружи, главное иметь доступ к этому результату без дополнительных триггеров фокус/блюр. Было бы удобно иметь доступ к результату валидации всей формы.

2021-11-08 10:38 UTC, bhoodream requested changes
Хорошая работа над ошибками! Есть еще некоторые проблемы и вопросы, с которыми было бы хорошо еще поработать.

Помимо коментов по коду, заметил еще такую проблему с кнопкой формы:

https://user-images.githubusercontent.com/1740470/140727616-ea8771e2-5887-4af6-ae13-d1ee54959d82.mov

2021-11-08 10:38 UTC, bhoodream commented on src/pages/chat/chat-control-button/chat-control-button.ts
> +          console.log('hello');
Hello :)

2021-11-08 10:38 UTC, bhoodream commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Подскажи, зачем нам потребовались вложенные ивенты? Выглядит как неоправданное усложнение...

2021-11-08 10:38 UTC, bhoodream commented on src/modules/block.ts
> +    document.querySelector(`[data-id='${this.id}']`)?.replaceWith(this._element);
Есть подозрение, что такой подход приведет к неожиданному поведению, например фокус в инпутах будет слетать, или еще какая информация. Мне все таки не понятно что ты тут пытаешься сделать...

2021-11-08 10:38 UTC, bhoodream commented on src/modules/misc.ts
> +export function isAllInputsValid() {
Лучше не создавать такие неопределенные наборы утилит, типа `misc`. Надо все же дробить по смыслу, здесь я вижу утилиты по теме `validation` и `forms`.

2021-11-08 10:58 UTC, aberezin97 commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Чтобы можно было при создании наследованных от block еще навешивать

2021-11-08 10:59 UTC, aberezin97 commented on src/modules/block.ts
> +    document.querySelector(`[data-id='${this.id}']`)?.replaceWith(this._element);
Хотелось бы, чтобы он создавал элемент на основании того, что в шаблоне

2021-11-08 11:24 UTC, aberezin97 commented on src/pages/chat/chat-control-button/chat-control-button.ts
> +          console.log('hello');
:)

2021-11-08 12:19 UTC, aberezin97 commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
![Animation2](https://user-images.githubusercontent.com/91316392/140740848-42e5e965-9947-4ad2-8d39-b6e5b9187073.gif)

2021-11-09 07:47 UTC, bhoodream commented on src/components/button/button.ts
> +    super('div', props);
ok

2021-11-09 07:48 UTC, bhoodream commented on src/modules/block.ts
> +    if (oldProps) return true;
ok

2021-11-09 07:48 UTC, bhoodream commented on src/modules/block.ts
> +    this.props = this._makePropsProxy({ ...props, __id: this._id });
ok

2021-11-09 07:48 UTC, bhoodream commented on src/pages/chat/index.ts
> +setTimeout(() => {
а, в таком случае это лучше удалить

2021-11-09 07:51 UTC, bhoodream commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
хм, да вообще он у меня всегда чистится с открытой консолью... интересно что у тебя такого поведения нет. Подскажи, в каком браузере проверяешь?

2021-11-09 07:52 UTC, bhoodream commented on src/modules/block.ts
> +    document.querySelector(`[data-id='${this.id}']`)?.replaceWith(this._element);
ок

2021-11-09 07:59 UTC, bhoodream commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
мда, что то странное у тебя происходит с билдом. Щас удалил старый `./dist`, пересобрал, и проблема реально ушла. Нужно при `build/dev` подчищать старый дист.

2021-11-09 08:01 UTC, aberezin97 commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
> хм, да вообще он у меня всегда чистится с открытой консолью... интересно что у тебя такого поведения нет. Подскажи, в каком браузере проверяешь?

Проверял в хроме и лисе 🙂

2021-11-09 08:26 UTC, bhoodream commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Обрати плиз внимание на этот коммент
> Щас удалил старый ./dist, пересобрал, и проблема реально ушла. Нужно при build/dev подчищать старый дист.

2021-11-09 08:27 UTC, aberezin97 commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Сделал, правда не кросс платформенное, на винде работать не будет)

2021-11-09 08:30 UTC, bhoodream commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Тогда сдавай :)

P.S. для винды можно было этот пакет юзануть https://www.npmjs.com/package/rimraf . Однако, я очень редко встречаю разработчиков на винде, возможно в этом никогда необходимости и не возникнет.

2021-11-09 08:33 UTC, aberezin97 commented on src/modules/block.ts
> +      if (typeof events[eventName] === 'object') this._addEvents(events[eventName]);
Хорошо) Да я тоже даже под виндой в wsl сижу, пускай страдают :D

2021-11-09 08:47 UTC, bhoodream commented
От меня АПРУВ!

P.S. если не хочешь чтобы пользователи тебя материли, покажи ошибки ввода на полях, я только по регулярке понял, что требуется в поле "пароль"! :)

2021-11-09 08:58 UTC, aberezin97 commented
> От меня АПРУВ!
> 
> 
> 
> P.S. если не хочешь чтобы пользователи тебя материли, покажи ошибки ввода на полях. Я только по регулярке понял, что требуется в поле "пароль"! :)

С меня лайк 👍 обязательно сделаю 🙂

2022-09-13 07:00 UTC, closed without merging